# coding=utf-8

from django.forms import Form, CharField, MultipleChoiceField

from bdr.forms import ComboTextInput


class DrugBank43FormatExportOptionsForm(Form):
    """
    Presents the user with common options used to export data.
    """

    COMMENT_DEFAULT = "#"
    COMMENT_CHOICES = [("#", "Hash (#)"), (";", "Semicolon (;)"), ("None", "None"), ("", "Other:")]
    ESCAPE_DEFAULT = "\\"
    ESCAPE_CHOICES = [("\\", "Backslash (\\)"), ("None", "None"), ("", "Other:")]
    QUOTE_DEFAULT = "\""
    QUOTE_CHOICES = [("\"", "Quotation mark (\")"), ("'", "Apostrophe (')"), ("|", "Pipe (|)"), ("None", "None"),
                     ("", "Other:")]
    SEPARATOR_DEFAULT = ","
    SEPARATOR_CHOICES = [("\t", "Tab"), (" ", "Space"), (",", "Comma (,)"), (";", "Semicolon (;)"), ("|", "Pipe (|)"),
                         ("", "Other:")]
    TERMINATOR_DEFAULT = "LF"
    TERMINATOR_CHOICES = [("LF", "Linux (LF)"), ("CRLF", "Windows (CRLF)"), ("CR", "Mac (CR)"), ("", "Other:")]
    TERMINATOR_CHARACTER_MAP = {
        "LF": "\n",
        "CRLF": "\r\n",
        "CR": "\r"
    }

    separator = CharField(max_length=1,
                          widget=ComboTextInput(choices=SEPARATOR_CHOICES, default=SEPARATOR_DEFAULT),
                          help_text="Used to separate fields in a record.")
    comment = CharField(max_length=1, required=False,
                        widget=ComboTextInput(choices=COMMENT_CHOICES, default=COMMENT_DEFAULT),
                        help_text="Used to mark a line as a comment.")
    quote = CharField(max_length=1, required=False,
                      widget=ComboTextInput(choices=QUOTE_CHOICES, default=QUOTE_DEFAULT),
                      help_text="If fields may contain special characters, select the character used to quote those"
                                " values.")
    escape = CharField(max_length=1, required=False,
                       widget=ComboTextInput(choices=ESCAPE_CHOICES, default=ESCAPE_DEFAULT),
                       help_text="If quotes are not used, select the character used to escape special characters. If"
                                 " quotes are used and no escape character is chosen, embedded quotes are doubled (for"
                                 " example, \"It's a test!\" would be saved as 'It''s a test!' when using single"
                                 " quotes).")
    line_terminator = CharField(widget=ComboTextInput(choices=TERMINATOR_CHOICES, default=TERMINATOR_DEFAULT),
                                help_text="Used to separate records.")

    @property
    def cleaned_metadata(self):
        """Validated options for exporting simple formatted data."""
        if not self.is_valid():
            raise AttributeError("'{:s}' object has no attribute 'cleaned_metadata'".format(self.__class__.__name__))
        metadata = {key: value for key, value in self.cleaned_data.items() if key not in ["name"]}
        if metadata["line_terminator"] in self.TERMINATOR_CHARACTER_MAP:
            metadata["line_terminator"] = self.TERMINATOR_CHARACTER_MAP[metadata["line_terminator"]]
        return metadata


class DrugBank43FieldSelectionForm(Form):

    ELEMENTS = (
        ('drug@created', 'Record created'),
        ('drug@type', 'Drug type'),
        ('drug@updated', 'Record updated'),
        ('drug/drugbank-id', u'DrugBank identifier [1…*]'),
        ('drug/drugbank-id@primary', 'Primary identifier?'),
        ('drug/name', 'Name'),
        ('drug/description', 'Description'),
        ('drug/cas-number', 'CAS registry number'),
        # ('drug/groups', 'Groups'),
        ('drug/groups/group', u'Drug group [1…6]'),
        ('drug/general-references', 'General references'),
        ('drug/synthesis-reference', 'Synthesis reference'),
        ('drug/indication', 'Indication'),
        ('drug/pharmacodynamics', 'Pharmacodynamics'),
        ('drug/mechanism-of-action', 'Mechanism of action'),
        ('drug/toxicity', 'Toxicity'),
        ('drug/metabolism', 'Metabolism'),
        ('drug/absorption', 'Absorption'),
        ('drug/half-life', 'Half-life'),
        ('drug/protein-binding', 'Protein binding'),
        ('drug/route-of-elimination', 'Route of elimination'),
        ('drug/volume-of-distribution', 'Volume of distribution'),
        ('drug/clearance', 'Clearance'),
        # ('drug/classification', u'Taxonomic classification [0…1]'),
        ('drug/classification/description', 'Classification description'),
        ('drug/classification/direct-parent', 'Classification parent'),
        ('drug/classification/kingdom', 'Classification kingdom'),
        ('drug/classification/superclass', 'Classification superclass'),
        ('drug/classification/class', 'Classification class'),
        ('drug/classification/subclass', 'Classification subclass'),
        ('drug/classification/alternative-parent', u'Alternative classification parent [0…*]'),
        ('drug/classification/substituent', u'Substituent [0…*]'),
        # ('drug/salts', 'Salts'),
        ('drug/salts/salt', u'Salt [0…*]'),
        ('drug/salts/salt/drugbank-id', u'Salt DrugBank identifier [0…*]'),
        ('drug/salts/salt/name', 'Salt name'),
        ('drug/salts/salt/cas-number', 'Salt CAS registry number'),
        ('drug/salts/salt/inchikey', 'International chemical identifier (hashed)'),
        # ('drug/synonyms', 'Synonyms'),
        ('drug/synonyms/synonym', u'Synonym [0…*]'),
        ('drug/synonyms/synonym@language', 'Synonym language'),
        ('drug/synonyms/synonym@coder', 'Synonym coder'),
        # ('drug/products', 'Products'),
        # ('drug/products/product', 'Product [0…*]'),
        ('drug/products/product/name', 'Product name'),
        ('drug/products/product/ndc-id', 'Product NDC identifier'),
        ('drug/products/product/ndc-product-code', 'Product NCD product code'),
        ('drug/products/product/dpd-id', 'Product DPD identifier'),
        ('drug/products/product/started-marketing-on', 'Start date of product marketing'),
        ('drug/products/product/ended-marketing-on', 'End date of product marketing'),
        ('drug/products/product/dosage-form', 'Product dosage form'),
        ('drug/products/product/strength', 'Product strength'),
        ('drug/products/product/route', 'Product route'),
        ('drug/products/product/fda-application-number', 'Product FDA application number'),
        ('drug/products/product/generic', 'Generic product?'),
        ('drug/products/product/over-the-counter', 'Over the counter product?'),
        ('drug/products/product/approved', 'Approved product?'),
        ('drug/products/product/country', 'Country of product origin'),
        ('drug/products/product/source', 'Source database for product'),
        # ('drug/international-brands', 'International brands'),
        # ('drug/international-brands/international-brand', u'International brand [0…*]'),
        ('drug/international-brands/international-brand/name', 'International brand name'),
        ('drug/international-brands/international-brand/company', 'International brand company'),
        # ('drug/mixtures', 'Mixtures'),
        # ('drug/mixtures/mixture', u'Mixture [0…*]'),
        ('drug/mixtures/mixture/name', 'Mixture name'),
        ('drug/mixtures/mixture/ingredients', 'Mixture ingredients'),
        # ('drug/packagers', 'Packagers'),
        # ('drug/packagers/packager', u'Packager [0…*]'),
        ('drug/packagers/packager/name', 'Packager name'),
        ('drug/packagers/packager/url', 'Packager URL'),
        # ('drug/manufacturers', 'Manufacturers'),
        ('drug/manufacturers/manufacturer', u'Manufacturer [0…*]'),
        ('drug/manufacturers/manufacturer@generic', 'Generic manufacturer?'),
        # ('drug/prices', 'Prices'),
        # ('drug/prices/price', u'Price [0…*]'),
        ('drug/prices/price/description', 'Price description'),
        ('drug/prices/price/cost', 'Cost'),
        ('drug/prices/price/cost@currency', 'Currency'),
        ('drug/prices/price/price', 'Price unit'),
        # ('drug/categories', 'Categories'),
        # ('drug/categories/category', u'Category [0…*]'),
        ('drug/categories/category/category', 'Category'),
        ('drug/categories/category/mesh-id', 'Category MeSH identifier'),
        # ('drug/affected-organisms', 'Affected organisms'),
        ('drug/affected-organisms/affected-organism', u'Affected organism [0…*]'),
        # ('drug/dosages', 'Dosages'),
        # ('drug/dosages/dosage', u'Dosage [0…*]'),
        ('drug/dosages/dosage/form', 'Dosage form'),
        ('drug/dosages/dosage/route', 'Dosage route'),
        ('drug/dosages/dosage/strength', 'Dosage strength'),
        # ('drug/atc-codes', 'ATC codes'),
        # ('drug/atc-codes/atc-code', u'ATC code [0…*]'),
        ('drug/atc-codes/atc-code@code', 'ATC code'),
        ('drug/atc-codes/atc-code/level', 'ATC level [4]'),
        ('drug/atc-codes/atc-code/level@code', 'ATC level code'),
        # ('drug/ahfs-codes', 'AHFS codes'),
        ('drug/ahfs-codes/ahfs-code', u'AHFS code [0…*]'),
        # ('drug/patents', 'Patents'),
        # ('drug/patents/patent', u'Patent [0…*]'),
        ('drug/patents/patent/number', 'Patent number'),
        ('drug/patents/patent/country', 'Country of patent registration'),
        ('drug/patents/patent/approved', 'Patent approval'),
        ('drug/patents/patent/expires', 'Patent expiry'),
        # ('drug/food-interactions', 'Food interactions'),
        ('drug/food-interaction/food-interaction', u'Food interaction [0…*]'),
        # ('drug/drug-interactions', 'Drug interactions'),
        # ('drug/drug-interactions/drug-interaction', u'Drug interaction [0…*]'),
        ('drug/drug-interactions/drug-interaction/drugbank-id', 'Interactor DrugBank identifier'),
        ('drug/drug-interactions/drug-interaction/drugbank-id@primary', 'Primary identifier of interactor?'),
        ('drug/drug-interactions/drug-interaction/name', 'Drug interaction name'),
        ('drug/drug-interactions/drug-interaction/description', 'Drug interaction description'),
        # ('drug/sequences', 'Sequences'),
        ('drug/sequences/sequence', u'Sequence [0…*]'),
        ('drug/sequences/sequence@format', 'Sequence format'),
        # ('drug/calculated-properties', u'Calculated properties [0…1]'),
        # ('drug/calculated-properties/property', u'Calculated property [0…*]'),
        ('drug/calculated-properties/property/kind', u'Calculated property kind'),
        ('drug/calculated-properties/property/value', u'Calculated property value'),
        ('drug/calculated-properties/property/source', u'Calculated property source'),
        # ('drug/experimental-properties', 'Experimental properties'),
        # ('drug/experimental-properties/property', u'Experimental property [0…*]'),
        ('drug/experimental-properties/property/kind', u'Experimental property kind'),
        ('drug/experimental-properties/property/value', u'Experimental property value'),
        ('drug/experimental-properties/property/source', u'Experimental property source'),
        # ('drug/external-identifiers', 'External identifiers'),
        # ('drug/external-identifiers/external-identifier', u'External identifier [0…*]'),
        ('drug/external-identifiers/external-identifier/resource', 'External identifier resource'),
        ('drug/external-identifiers/external-identifier/identifier', 'External identifier'),
        # ('drug/external-links', 'External links'),
        # ('drug/external-links/external-link', u'External link [0…*]'),
        ('drug/external-links/external-link/resource', 'External link resource'),
        ('drug/external-links/external-link/url', 'External link URL'),
        # ('drug/pathways', 'Pathways'),
        # ('drug/pathways/pathway', u'Pathway [0…*]'),
        ('drug/pathways/pathway/smpdb-id', 'SMPDB identifier'),
        ('drug/pathways/pathway/name', 'Pathway name'),
        # ('drug/pathways/pathway/drugs', 'Pathway drugs'),
        # ('drug/pathways/pathway/drugs/drug', u'Pathway drug [1…*]'),
        ('drug/pathways/pathway/drugs/drug/drugbank-id', 'Pathway drug DrugBank identifier'),
        ('drug/pathways/pathway/drugs/drug/drugbank-id@primary', 'Primary pathway drug DrugBank identifier?'),
        ('drug/pathways/pathway/drugs/drug/name', 'Pathway drug name'),
        # ('drug/pathways/pathway/enzymes', 'Pathway enzymes'),
        ('drug/pathways/pathway/enzymes/uniprot-id', u'Pathway enzyme UniProt identifier [0…*]'),
        # ('drug/reactions', 'Reactions'),
        # ('drug/reactions/reaction', u'Reaction [0…*]'),
        ('drug/reactions/reaction/sequence', 'Reaction sequence'),
        # ('drug/reactions/reaction/left-element', 'Left reaction element'),
        ('drug/reactions/reaction/left-element/drugbank-id', 'DrugBank identifier for left reaction element'),
        ('drug/reactions/reaction/left-element/name', 'Left reaction element name'),
        ('drug/reactions/reaction/right-element', 'Right reaction element'),
        ('drug/reactions/reaction/right-element/drugbank-id', 'DrugBank identifier for right reaction element'),
        ('drug/reactions/reaction/right-element/name', 'Right reaction element name'),
        # ('drug/reactions/reaction/enzymes', 'Reaction enzymes'),
        # ('drug/reactions/reaction/enzymes/enzyme', u'Reaction enzyme [0…*]'),
        ('drug/reactions/reaction/enzymes/enzyme/drugbank-id', 'Reaction enzyme DrugBank identifier'),
        ('drug/reactions/reaction/enzymes/enzyme/name', 'Reaction enzyme name'),
        ('drug/reactions/reaction/enzymes/enzyme/uniprot-id', 'Reaction enzyme UniProt identifier'),
        # ('drug/snp-effects', 'SNP effects'),
        # ('drug/snp-effects/effect', u'SNP effect [0…*]'),
        ('drug/snp-effects/effect/protein-name', 'SNP effect protein name'),
        ('drug/snp-effects/effect/gene-symbol', 'SNP effect gene symbol'),
        ('drug/snp-effects/effect/uniprot-id', 'SNP effect UniProt identifier'),
        ('drug/snp-effects/effect/rs-id', 'SNP effect RS identifier'),
        ('drug/snp-effects/effect/allele', 'SNP effect allele'),
        ('drug/snp-effects/effect/defining-change', 'Defining change of SNP effect'),
        ('drug/snp-effects/effect/description', 'SNP effect description'),
        ('drug/snp-effects/effect/pubmed-id', 'PubMed identifier for SNP effect'),
        # ('drug/snp-adverse-drug-reactions', 'Adverse SNP drug reactions'),
        # ('drug/snp-adverse-drug-reactions/reaction', u'Adverse SNP drug reactions [0…*]'),
        ('drug/snp-adverse-drug-reactions/reaction/protein-name', 'SNP adverse drug reaction protein name'),
        ('drug/snp-adverse-drug-reactions/reaction/gene-symbol', 'SNP adverse drug reaction gene symbol'),
        ('drug/snp-adverse-drug-reactions/reaction/uniprot-id', 'SNP adverse drug reaction UniProt identifier'),
        ('drug/snp-adverse-drug-reactions/reaction/rs-id', 'SNP adverse drug reaction RS identifier'),
        ('drug/snp-adverse-drug-reactions/reaction/allele', 'SNP adverse drug reaction allele'),
        ('drug/snp-adverse-drug-reactions/reaction/defining-change', 'Defining change of SNP adverse drug reaction'),
        ('drug/snp-adverse-drug-reactions/reaction/description', 'SNP adverse drug reaction description'),
        ('drug/snp-adverse-drug-reactions/reaction/pubmed-id', 'PubMed identifier for SNP adverse drug reaction'),
        # ('drug/targets', 'Targets'),
        # ('drug/targets/target', u'Target [0…*]'),
        ('drug/targets/target@position', 'Target position'),
        ('drug/targets/target/id', 'Target identifier'),
        ('drug/targets/target/name', 'Target name'),
        ('drug/targets/target/organism', 'Target organism'),
        # ('drug/targets/target/actions', 'Target actions'),
        ('drug/targets/target/actions/action', u'Target action [0…*]'),
        ('drug/targets/target/references', 'Target references'),
        ('drug/targets/target/known-action', 'Target action known'),
        # ('drug/targets/target/polypeptide', u'Target polypeptide [0…*]'),
        ('drug/targets/target/polypeptide@id', 'Target polypeptide identifier'),
        ('drug/targets/target/polypeptide@source', 'Target polypeptide source'),
        ('drug/targets/target/polypeptide/name', 'Target polypeptide name'),
        ('drug/targets/target/polypeptide/general-function', 'General function of target polypeptide'),
        ('drug/targets/target/polypeptide/specific-function', 'Specific function of target polypeptide'),
        ('drug/targets/target/polypeptide/gene-name', 'Target polypeptide gene name'),
        ('drug/targets/target/polypeptide/locus', 'Target polypeptide locus'),
        ('drug/targets/target/polypeptide/cellular-location', 'Target polypeptide cellular location'),
        ('drug/targets/target/polypeptide/transmembrane-regions', 'Target polypeptide transmembrane regions'),
        ('drug/targets/target/polypeptide/signal-regions', 'Target polypeptide signal regions'),
        ('drug/targets/target/polypeptide/theoretical-pi', 'Target polypeptide pI'),
        ('drug/targets/target/polypeptide/molecular-weight', 'Molecular weight of target polypeptide'),
        ('drug/targets/target/polypeptide/chromosome-location', 'Target polypeptide chromosome location'),
        ('drug/targets/target/polypeptide/organism', 'Target polypeptide organism'),
        ('drug/targets/target/polypeptide/organism@ncbi-taxonomy-id',
         'Target polypeptide organism NCBI taxonomy identifier'),
        # ('drug/targets/target/polypeptide/external-identifiers', 'Target polypeptide external identifiers'),
        # ('drug/targets/target/polypeptide/external-identifiers/external-identifier',
        #  u'Target polypeptide external identifiers [0…*]'),
        ('drug/targets/target/polypeptide/external-identifiers/external-identifier/resource',
         'Target polypeptide external identifier resource'),
        ('drug/targets/target/polypeptide/external-identifiers/external-identifier/identifier',
         'Target polypeptide external identifier'),
        # ('drug/targets/target/polypeptide/synonyms', 'Target polypeptide synonyms'),
        ('drug/targets/target/polypeptide/synonyms/synonym', u'Target polypeptide synonym [0…*]'),
        ('drug/targets/target/polypeptide/amino-acid-sequence', 'Target polypeptide amino acid sequence'),
        ('drug/targets/target/polypeptide/amino-acid-sequence@format', 'Target polypeptide amino acid sequence format'),
        ('drug/targets/target/polypeptide/gene-sequence', 'Target polypeptide gene sequence'),
        ('drug/targets/target/polypeptide/gene-sequence@format', 'Target polypeptide gene sequence format'),
        # ('drug/targets/target/polypeptide/pfams', 'Target polypeptide protein families'),
        # ('drug/targets/target/polypeptide/pfams/pfam', u'Target polypeptide protein family [0…*]'),
        ('drug/targets/target/polypeptide/pfams/pfam/identifier', 'Target polypeptide protein family identifier'),
        ('drug/targets/target/polypeptide/pfams/pfam/name', 'Target polypeptide protein family name'),
        # ('drug/targets/target/polypeptide/go-classifiers', 'Target polypeptide GO classifiers'),
        # ('drug/targets/target/polypeptide/go-classifiers/go-classifier', u'Target polypeptide GO classifier [0…*]'),
        ('drug/targets/target/polypeptide/go-classifiers/go-classifier/category',
         'Target polypeptide GO classifier category'),
        ('drug/targets/target/polypeptide/go-classifiers/go-classifier/description',
         'Target polypeptide GO classifier description'),
        # ('drug/enzymes', 'Enzymes'),
        # ('drug/enzymes/enzyme', u'Enzyme [0…*]'),
        ('drug/enzymes/enzyme@position', 'Enzyme position'),
        ('drug/enzymes/enzyme/id', 'Enzyme identifier'),
        ('drug/enzymes/enzyme/name', 'Enzyme name'),
        ('drug/enzymes/enzyme/organism', 'Enzyme organism'),
        # ('drug/enzymes/enzyme/actions', 'Enzyme actions'),
        ('drug/enzymes/enzyme/actions/action', u'Enzyme action [0…*]'),
        ('drug/enzymes/enzyme/references', 'Enzyme references'),
        ('drug/enzymes/enzyme/known-action', 'Enzyme action known'),
        # ('drug/enzymes/enzyme/polypeptide', u'Enzyme polypeptide [0…*]'),
        ('drug/enzymes/enzyme/polypeptide@id', 'Enzyme polypeptide identifier'),
        ('drug/enzymes/enzyme/polypeptide@source', 'Enzyme polypeptide source'),
        ('drug/enzymes/enzyme/polypeptide/name', 'Enzyme polypeptide name'),
        ('drug/enzymes/enzyme/polypeptide/general-function', 'General function of enzyme polypeptide'),
        ('drug/enzymes/enzyme/polypeptide/specific-function', 'Specific function of enzyme polypeptide'),
        ('drug/enzymes/enzyme/polypeptide/gene-name', 'Enzyme polypeptide gene name'),
        ('drug/enzymes/enzyme/polypeptide/locus', 'Enzyme polypeptide locus'),
        ('drug/enzymes/enzyme/polypeptide/cellular-location', 'Enzyme polypeptide cellular location'),
        ('drug/enzymes/enzyme/polypeptide/transmembrane-regions', 'Enzyme polypeptide transmembrane regions'),
        ('drug/enzymes/enzyme/polypeptide/signal-regions', 'Enzyme polypeptide signal regions'),
        ('drug/enzymes/enzyme/polypeptide/theoretical-pi', 'Enzyme polypeptide pI'),
        ('drug/enzymes/enzyme/polypeptide/molecular-weight', 'Molecular weight of enzyme polypeptide'),
        ('drug/enzymes/enzyme/polypeptide/chromosome-location', 'Enzyme polypeptide chromosome location'),
        ('drug/enzymes/enzyme/polypeptide/organism', 'Enzyme polypeptide organism'),
        ('drug/enzymes/enzyme/polypeptide/organism@ncbi-taxonomy-id',
         'Enzyme polypeptide organism NCBI taxonomy identifier'),
        # ('drug/enzymes/enzyme/polypeptide/external-identifiers', 'Enzyme polypeptide external identifiers'),
        # ('drug/enzymes/enzyme/polypeptide/external-identifiers/external-identifier',
        #  u'Enzyme polypeptide external identifiers [0…*]'),
        ('drug/enzymes/enzyme/polypeptide/external-identifiers/external-identifier/resource',
         'Enzyme polypeptide external identifier resource'),
        ('drug/enzymes/enzyme/polypeptide/external-identifiers/external-identifier/identifier',
         'Enzyme polypeptide external identifier'),
        # ('drug/enzymes/enzyme/polypeptide/synonyms', 'Enzyme polypeptide synonyms'),
        ('drug/enzymes/enzyme/polypeptide/synonyms/synonym', u'Enzyme polypeptide synonym [0…*]'),
        ('drug/enzymes/enzyme/polypeptide/amino-acid-sequence', 'Enzyme polypeptide amino acid sequence'),
        ('drug/enzymes/enzyme/polypeptide/amino-acid-sequence@format', 'Enzyme polypeptide amino acid sequence format'),
        ('drug/enzymes/enzyme/polypeptide/gene-sequence', 'Enzyme polypeptide gene sequence'),
        ('drug/enzymes/enzyme/polypeptide/gene-sequence@format', 'Enzyme polypeptide gene sequence format'),
        # ('drug/enzymes/enzyme/polypeptide/pfams', 'Enzyme polypeptide protein families'),
        # ('drug/enzymes/enzyme/polypeptide/pfams/pfam', u'Enzyme polypeptide protein family [0…*]'),
        ('drug/enzymes/enzyme/polypeptide/pfams/pfam/identifier', 'Enzyme polypeptide protein family identifier'),
        ('drug/enzymes/enzyme/polypeptide/pfams/pfam/name', 'Enzyme polypeptide protein family name'),
        # ('drug/enzymes/enzyme/polypeptide/go-classifiers', 'Enzyme polypeptide GO classifiers'),
        # ('drug/enzymes/enzyme/polypeptide/go-classifiers/go-classifier', u'Enzyme polypeptide GO classifier [0…*]'),
        ('drug/enzymes/enzyme/polypeptide/go-classifiers/go-classifier/category',
         'Enzyme polypeptide GO classifier category'),
        ('drug/enzymes/enzyme/polypeptide/go-classifiers/go-classifier/description',
         'Enzyme polypeptide GO classifier description'),
        ('drug/enzymes/enzyme/inhibition-strength', 'Enzyme inhibition strength'),
        ('drug/enzymes/enzyme/induction-strength', 'Enzyme induction strength'),
        # ('drug/carriers', 'Carriers'),
        # ('drug/carriers/carrier', u'Carrier [0…*]'),
        ('drug/carriers/carrier@position', 'Carrier position'),
        ('drug/carriers/carrier/id', 'Carrier identifier'),
        ('drug/carriers/carrier/name', 'Carrier name'),
        ('drug/carriers/carrier/organism', 'Carrier organism'),
        # ('drug/carriers/carrier/actions', 'Carrier actions'),
        ('drug/carriers/carrier/actions/action', u'Carrier action [0…*]'),
        ('drug/carriers/carrier/references', 'Carrier references'),
        ('drug/carriers/carrier/known-action', 'Carrier action known'),
        # ('drug/carriers/carrier/polypeptide', u'Carrier polypeptide [0…*]'),
        ('drug/carriers/carrier/polypeptide@id', 'Carrier polypeptide identifier'),
        ('drug/carriers/carrier/polypeptide@source', 'Carrier polypeptide source'),
        ('drug/carriers/carrier/polypeptide/name', 'Carrier polypeptide name'),
        ('drug/carriers/carrier/polypeptide/general-function', 'General function of carrier polypeptide'),
        ('drug/carriers/carrier/polypeptide/specific-function', 'Specific function of carrier polypeptide'),
        ('drug/carriers/carrier/polypeptide/gene-name', 'Carrier polypeptide gene name'),
        ('drug/carriers/carrier/polypeptide/locus', 'Carrier polypeptide locus'),
        ('drug/carriers/carrier/polypeptide/cellular-location', 'Carrier polypeptide cellular location'),
        ('drug/carriers/carrier/polypeptide/transmembrane-regions', 'Carrier polypeptide transmembrane regions'),
        ('drug/carriers/carrier/polypeptide/signal-regions', 'Carrier polypeptide signal regions'),
        ('drug/carriers/carrier/polypeptide/theoretical-pi', 'Carrier polypeptide pI'),
        ('drug/carriers/carrier/polypeptide/molecular-weight', 'Molecular weight of carrier polypeptide'),
        ('drug/carriers/carrier/polypeptide/chromosome-location', 'Carrier polypeptide chromosome location'),
        ('drug/carriers/carrier/polypeptide/organism', 'Carrier polypeptide organism'),
        ('drug/carriers/carrier/polypeptide/organism@ncbi-taxonomy-id',
         'Carrier polypeptide organism NCBI taxonomy identifier'),
        # ('drug/carriers/carrier/polypeptide/external-identifiers', 'Carrier polypeptide external identifiers'),
        # ('drug/carriers/carrier/polypeptide/external-identifiers/external-identifier',
        #  u'Carrier polypeptide external identifiers [0…*]'),
        ('drug/carriers/carrier/polypeptide/external-identifiers/external-identifier/resource',
         'Carrier polypeptide external identifier resource'),
        ('drug/carriers/carrier/polypeptide/external-identifiers/external-identifier/identifier',
         'Carrier polypeptide external identifier'),
        # ('drug/carriers/carrier/polypeptide/synonyms', 'Carrier polypeptide synonyms'),
        ('drug/carriers/carrier/polypeptide/synonyms/synonym', u'Carrier polypeptide synonym [0…*]'),
        ('drug/carriers/carrier/polypeptide/amino-acid-sequence', 'Carrier polypeptide amino acid sequence'),
        ('drug/carriers/carrier/polypeptide/amino-acid-sequence@format',
         'Carrier polypeptide amino acid sequence format'),
        ('drug/carriers/carrier/polypeptide/gene-sequence', 'Carrier polypeptide gene sequence'),
        ('drug/carriers/carrier/polypeptide/gene-sequence@format', 'Carrier polypeptide gene sequence format'),
        # ('drug/carriers/carrier/polypeptide/pfams', 'Carrier polypeptide protein families'),
        # ('drug/carriers/carrier/polypeptide/pfams/pfam', u'Carrier polypeptide protein family [0…*]'),
        ('drug/carriers/carrier/polypeptide/pfams/pfam/identifier', 'Carrier polypeptide protein family identifier'),
        ('drug/carriers/carrier/polypeptide/pfams/pfam/name', 'Carrier polypeptide protein family name'),
        # ('drug/carriers/carrier/polypeptide/go-classifiers', 'Carrier polypeptide GO classifiers'),
        # ('drug/carriers/carrier/polypeptide/go-classifiers/go-classifier',
        #  u'Carrier polypeptide GO classifier [0…*]'),
        ('drug/carriers/carrier/polypeptide/go-classifiers/go-classifier/category',
         'Carrier polypeptide GO classifier category'),
        ('drug/carriers/carrier/polypeptide/go-classifiers/go-classifier/description',
         'Carrier polypeptide GO classifier description'),
        # ('drug/transporters', 'Transporters'),
        # ('drug/transporters/transporter', u'Transporter [0…*]'),
        ('drug/transporters/transporter@position', 'Transporter position'),
        ('drug/transporters/transporter/id', 'Transporter identifier'),
        ('drug/transporters/transporter/name', 'Transporter name'),
        ('drug/transporters/transporter/organism', 'Transporter organism'),
        # ('drug/transporters/transporter/actions', 'Transporter actions'),
        ('drug/transporters/transporter/actions/action', u'Transporter action [0…*]'),
        ('drug/transporters/transporter/references', 'Transporter references'),
        ('drug/transporters/transporter/known-action', 'Transporter action known'),
        # ('drug/transporters/transporter/polypeptide', u'Transporter polypeptide [0…*]'),
        ('drug/transporters/transporter/polypeptide@id', 'Transporter polypeptide identifier'),
        ('drug/transporters/transporter/polypeptide@source', 'Transporter polypeptide source'),
        ('drug/transporters/transporter/polypeptide/name', 'Transporter polypeptide name'),
        ('drug/transporters/transporter/polypeptide/general-function', 'General function of transporter polypeptide'),
        ('drug/transporters/transporter/polypeptide/specific-function', 'Specific function of transporter polypeptide'),
        ('drug/transporters/transporter/polypeptide/gene-name', 'Transporter polypeptide gene name'),
        ('drug/transporters/transporter/polypeptide/locus', 'Transporter polypeptide locus'),
        ('drug/transporters/transporter/polypeptide/cellular-location', 'Transporter polypeptide cellular location'),
        ('drug/transporters/transporter/polypeptide/transmembrane-regions',
         'Transporter polypeptide transmembrane regions'),
        ('drug/transporters/transporter/polypeptide/signal-regions', 'Transporter polypeptide signal regions'),
        ('drug/transporters/transporter/polypeptide/theoretical-pi', 'Transporter polypeptide pI'),
        ('drug/transporters/transporter/polypeptide/molecular-weight', 'Molecular weight of transporter polypeptide'),
        ('drug/transporters/transporter/polypeptide/chromosome-location',
         'Transporter polypeptide chromosome location'),
        ('drug/transporters/transporter/polypeptide/organism', 'Transporter polypeptide organism'),
        ('drug/transporters/transporter/polypeptide/organism@ncbi-taxonomy-id',
         'Transporter polypeptide organism NCBI taxonomy identifier'),
        # ('drug/transporters/transporter/polypeptide/external-identifiers',
        #  'Transporter polypeptide external identifiers'),
        # ('drug/transporters/transporter/polypeptide/external-identifiers/external-identifier',
        #  u'Transporter polypeptide external identifiers [0…*]'),
        ('drug/transporters/transporter/polypeptide/external-identifiers/external-identifier/resource',
         'Transporter polypeptide external identifier resource'),
        ('drug/transporters/transporter/polypeptide/external-identifiers/external-identifier/identifier',
         'Transporter polypeptide external identifier'),
        # ('drug/transporters/transporter/polypeptide/synonyms', 'Transporter polypeptide synonyms'),
        ('drug/transporters/transporter/polypeptide/synonyms/synonym', u'Transporter polypeptide synonym [0…*]'),
        ('drug/transporters/transporter/polypeptide/amino-acid-sequence',
         'Transporter polypeptide amino acid sequence'),
        ('drug/transporters/transporter/polypeptide/amino-acid-sequence@format',
         'Transporter polypeptide amino acid sequence format'),
        ('drug/transporters/transporter/polypeptide/gene-sequence', 'Transporter polypeptide gene sequence'),
        ('drug/transporters/transporter/polypeptide/gene-sequence@format',
         'Transporter polypeptide gene sequence format'),
        # ('drug/transporters/transporter/polypeptide/pfams', 'Transporter polypeptide protein families'),
        # ('drug/transporters/transporter/polypeptide/pfams/pfam', u'Transporter polypeptide protein family [0…*]'),
        ('drug/transporters/transporter/polypeptide/pfams/pfam/identifier',
         'Transporter polypeptide protein family identifier'),
        ('drug/transporters/transporter/polypeptide/pfams/pfam/name', 'Transporter polypeptide protein family name'),
        # ('drug/transporters/transporter/polypeptide/go-classifiers', 'Transporter polypeptide GO classifiers'),
        # ('drug/transporters/transporter/polypeptide/go-classifiers/go-classifier',
        #  u'Transporter polypeptide GO classifier [0…*]'),
        ('drug/transporters/transporter/polypeptide/go-classifiers/go-classifier/category',
         'Transporter polypeptide GO classifier category'),
        ('drug/transporters/transporter/polypeptide/go-classifiers/go-classifier/description',
         'Transporter polypeptide GO classifier description'),
    )

    selected = MultipleChoiceField(ELEMENTS)
